[icons]
icons = "material-nf"

[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon  $ssid.str(max_w:12) $ip ($signal_strength) "

[[block]]
block = "disk_space"
path = "/"

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total "

[[block]]
block = "cpu"

[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $average avg, $max max "

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
