# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/67025056-10fd-41f4-88bf-a9eb396257de";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/5d364454-a09d-445d-9f01-70eb515422b7";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/767e23f7-018f-4652-93fe-40ab078c7f0f"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
