{ config, lib, ... }:
let
  cfg = config.modules.syncthing;

  # Central device registry. The device ID is generated by syncthing on first
  # run (tied to its TLS key) and is stable forever afterwards.
  #
  # To get a new device's ID:
  #   1. Enable this module on the host and apply the config (keys get generated).
  #   2. Run `syncthing --device-id` on that host, or open the GUI at
  #      http://127.0.0.1:8384 and use Actions -> Show ID.
  #   3. Paste the ID below and re-apply on all hosts.
  devices = {
    "tui" = { id = "3EEYNSK-IJ4YIX3-PHIEKT7-OECJJ2K-7RZAEZ7-TBY2AGW-HCKNPNH-34QYTQ6"; };
    "jjack-XMW16X" = { id = "IMQF5KD-ZGCQOZQ-GWPFWSN-2E3FH3O-UFOJL2Z-DBTS2AU-NVVAVYJ-XYNLJAG"; };
    # TODO: fill in once generated on first run (see comment above).
    "jrose-04LCLG" = { id = "MPJVTVB-LQYSFOC-SXERAID-MX4YVCY-2SKZHBQ-QDCV5Z2-6QL6DM2-7FQANAF"; };
    "kea" = { id = "FILL-ME-IN"; };
  };

  # Device groups for sharing. Adjust membership as machines come and go.
  personalDevices = [ "tui" "kea" ];
  allDevices = [ "tui" "kea" "jrose-04LCLG" "jjack-XMW16X" ];

  versioning = {
    type = "staggered";
    params = {
      cleanInterval = "3600";
      maxAge = "31536000";
    };
  };
in
{
  options.modules.syncthing = {
    enable = lib.mkEnableOption "Syncthing file synchronization";
  };

  config = lib.mkIf cfg.enable {
    # Cross-platform: the HM module uses a systemd user service on Linux and a
    # launchd agent on macOS. `~/` paths resolve to each host's home directory.
    services.syncthing = {
      enable = true;
      overrideDevices = true;
      overrideFolders = true;
      settings = {
        inherit devices;
        folders = {
          "Default" = {
            inherit versioning;
            path = "~/Sync";
            devices = personalDevices;
          };
          "Notes" = {
            inherit versioning;
            path = "~/notes";
            devices = allDevices;
          };
          "Documents" = {
            inherit versioning;
            path = "~/Documents";
            devices = allDevices;
          };
          "Calibre library" = {
            inherit versioning;
            path = "~/Calibre Library";
            devices = personalDevices;
          };
        };
      };
    };
  };
}
